apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microcron-ce.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.scripts }}
  {{ $key }}: |
{{ $value | indent 4 }}
{{- end }}
